/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foto_reporteria_2;

import Clases_Rasq.Mthod_Login_Pro;
import Clases_Rasq.Mtod_Ecriptacion;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jcarrierpigeon.Notification;
import net.sf.jcarrierpigeon.NotificationQueue;
import net.sf.jcarrierpigeon.WindowPosition;

/**
 *
 * @author Works
 */
public class Contraseña_perdida extends javax.swing.JFrame {

    Mthod_Login_Pro clas_login = new Mthod_Login_Pro();
    Mtod_Ecriptacion encript = new Mtod_Ecriptacion();
    
     byte keigenx[] = "ADJSSKLFJQQFSD@Low".getBytes();
    String usuario;
    String contra_generada;
    String respuesta_clase;
    String respuesta_txt;
    String pregunta_de_seguridad;
    String comprovador;
    int estado_contra;
    int estado_contrax;
    ImageIcon imagen;
    int desbloqueador; 

    public int getDesbloqueador() {
        return desbloqueador;
    }

    public void setDesbloqueador(int desbloqueador) {
        this.desbloqueador = desbloqueador;
    }
    
    
    /**
     * Creates new form Contraseña_perdida
     */
    public Contraseña_perdida() {
        initComponents();
        Notification obj = new  Notification(this, WindowPosition.BOTTOMRIGHT, 0, 0,1000000 );
        NotificationQueue val = new NotificationQueue();
        val.add(obj); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new org.edisoncor.gui.textField.TextFieldRound();
        txt_security = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonRound1 = new org.edisoncor.gui.button.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        txt_respuesta = new org.edisoncor.gui.textField.TextFieldRound();
        buttonRound2 = new org.edisoncor.gui.button.ButtonRound();
        txt_contra_temporal = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        panelCurves3 = new org.edisoncor.gui.panel.PanelCurves();
        btn_exit = new org.edisoncor.gui.label.LabelTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 38, 243, -1));
        getContentPane().add(txt_security, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 101, 373, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pregunta de seguridad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 103, -1, -1));

        buttonRound1.setText("Comprobar");
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 34, 120, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respuesta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 157, -1, -1));
        getContentPane().add(txt_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 155, 242, -1));

        buttonRound2.setText("Restaurar");
        buttonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 151, 120, -1));
        getContentPane().add(txt_contra_temporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 196, 373, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña temporal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 198, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 32, 48));

        panelCurves3.setForeground(new java.awt.Color(51, 255, 51));

        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Drag.png"))); // NOI18N
        btn_exit.setText("Salir");
        btn_exit.setAlignmentY(0.1F);
        btn_exit.setDescription(".");
        btn_exit.setEnabled(false);
        btn_exit.setIconTextGap(10);
        btn_exit.setRedondeado(true);
        btn_exit.setVerifyInputWhenFocusTarget(false);
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(538, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelCurves3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
     compro_user();
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void buttonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound2ActionPerformed
     compro_respuesta();     
    }//GEN-LAST:event_buttonRound2ActionPerformed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        Login_MT2_v2 log = new Login_MT2_v2();
        log.setVisible(true);
        this.hide();

    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked

    }//GEN-LAST:event_btn_exitMouseClicked

    
    
    
    public void compro_user()
    {
    if(txt_usuario.getText().length() ==0 )
    {
     JOptionPane.showMessageDialog(null, "Campo en blanco");
    }
    else
    {
    usuario = txt_usuario.getText();
    clas_login.setName_user(usuario);
    if(clas_login.consult_login())
    {
    pregunta_de_seguridad = clas_login.getPregunta_s();
    respuesta_clase = clas_login.getPregunta_respuesta();
    imagen = clas_login.getEm_url_bit();
    lbl_img.setIcon(imagen);
    txt_security.setText(pregunta_de_seguridad);
    txt_security.setEditable(false);
    txt_usuario.setEditable(false);
    
    }
    else
    {
        System.out.println("Error");
    
    }
         
    }
    
    
    }
    public void compro_respuesta()
    {
    if(txt_respuesta.getText().length() ==0)
    {
       JOptionPane.showMessageDialog(null, "Campo en blanco");
    }
    else
    {
      respuesta_txt = txt_respuesta.getText();
      if(respuesta_txt.equals(respuesta_clase))
      {
          generador_de_contraseñas(20);
          encript.keygen(keigenx);
          String  keygelen  = encript.encrypt(comprovador);
          txt_contra_temporal.setText(keygelen);
          txt_contra_temporal.setEditable(false);
          
          clas_login.setContraseña_temporal(keygelen);
          clas_login.setEstado_contra_act(1);
          clas_login.setName_user(usuario);
           if(clas_login.consult_login())
           {
           estado_contra = clas_login.getEstado_contra();
           System.out.println(""+ estado_contra);
           }
           else
           {
           }
          
           if(estado_contra == 1)
           {
           nicon.notify.core.Notification.show( usuario + " !!!",  "No es posible retablecer la contraseña" ,nicon.notify.core.Notification.NICON_DARK_THEME , nicon.notify.core.Notification.ERROR_MESSAGE ,10000);
           txt_contra_temporal.setText("");
           this.hide();
           Login_MT2_v2 load = new Login_MT2_v2();
           load.setVisible(true);
           }
           else
           {
          if(clas_login.Actualizar_contraseña())
          {
          
          nicon.notify.core.Notification.show( usuario + " !!!",  "Esta contraseña tendra un uso de 24 horas" ,nicon.notify.core.Notification.NICON_DARK_THEME , nicon.notify.core.Notification.SECURE_ICON ,10000);
          nicon.notify.core.Notification.show( usuario + " !!!",  "Se a notificado del cambio de contraseña" ,nicon.notify.core.Notification.NICON_DARK_THEME , nicon.notify.core.Notification.UPDATE_ICON_BLUE ,10000);
          }
          else
          {
          
          }
           }
          
        
      }
    }
      

    
    }
//---------------------------------------------------------------generador de contraseñas-----------------------------------------------------------------------------------    
String  generador_de_contraseñas(int longitud){ // se pide una longitud de datos para la contraseña
String cadenaAleatoria = ""; // se declara la variable cadena aleatoria
   
long milis = new java.util.GregorianCalendar().getTimeInMillis(); // 
Random r = new Random(milis);
int i = 0;
while ( i < longitud){  // se genera el ramdom de la letra a la z
char c = (char)r.nextInt(255);
if ( (c >= '0' && c <='9') || (c >='A' && c <='Z') ){ // se vadidan que sean letras y numeros 
cadenaAleatoria += c; // se retieneen la variable de la cadena aleatoria
i ++;// sigue contado 
}
}
//System.out.println("" + cadenaAleatoria);
comprovador = cadenaAleatoria;
return cadenaAleatoria;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contraseña_perdida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contraseña_perdida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contraseña_perdida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contraseña_perdida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña_perdida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.label.LabelTask btn_exit;
    private org.edisoncor.gui.button.ButtonRound buttonRound1;
    private org.edisoncor.gui.button.ButtonRound buttonRound2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_img;
    private org.edisoncor.gui.panel.PanelCurves panelCurves3;
    private org.edisoncor.gui.textField.TextFieldRound txt_contra_temporal;
    private org.edisoncor.gui.textField.TextFieldRound txt_respuesta;
    private org.edisoncor.gui.textField.TextFieldRound txt_security;
    private org.edisoncor.gui.textField.TextFieldRound txt_usuario;
    // End of variables declaration//GEN-END:variables
}
