/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Mantenimiento.Mto_Horario;
import java.sql.ResultSet;
//import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class Horario extends javax.swing.JFrame {

    //Variable pública
    String cod_horario;
    
    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
        settingtime();
        this.setLocationRelativeTo(null);
    }
    
    public void settingtime(){
        try {
            Calendar gc = new GregorianCalendar();
            int h1 = gc.get(gc.HOUR_OF_DAY);
            int m1 = gc.get(gc.MINUTE);
            jComboBox1.setSelectedIndex(h1);
            jComboBox2.setSelectedIndex(m1);
            
            //hora cierre
            if (m1 == 59){
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date d2 = df.parse("2016-05-30 " + (h1 + 1) + ":" +  "00:00");
                Calendar gc2 = new GregorianCalendar();
                gc2.setTime(d2);
                if (h1 > 23){
                    Date d3 = df.parse("2016-05-30 00:00:00");
                    gc2.setTime(d3);
                }
                int h2 = gc2.get(gc2.HOUR_OF_DAY);
                int m2 = gc2.get(gc2.MINUTE);
                jComboBox3.setSelectedIndex(h2);
                jComboBox4.setSelectedIndex(m2);
            } else {
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date d2 = df.parse("2016-05-30 " + h1 + ":" + (m1 + 1) + ":00");
                Calendar gc2 = new GregorianCalendar();
                gc2.setTime(d2);
                int h2 = gc2.get(gc2.HOUR_OF_DAY);
                int m2 = gc2.get(gc2.MINUTE);
                jComboBox3.setSelectedIndex(h2);
                jComboBox4.setSelectedIndex(m2);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Horario.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void mthLimpiarCampos(){
        jTextField2.setText("");
        jComboBox1.setSelectedIndex(1);
        jComboBox2.setSelectedIndex(1);
        jComboBox3.setSelectedIndex(1);
        jComboBox4.setSelectedIndex(1);
        cod_horario = null;
    }
    
    public void mthConsulta(){
        ResultSet res;
        Mto_Horario obj = new Mto_Horario();
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        res = obj.Consulta();
        dtm.setColumnIdentifiers(new Object[]{"Codigo", "Horario", "Hora apertura", "Hora cierre"});
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                dtm.addRow(v);
                jTable1.setModel(dtm);
                //oculta columnas innecesarias
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            }
            mthLimpiarCampos();
        }catch(Exception ex){

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_configuracion = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        lbl_usuario5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_configuracion.setBackground(new java.awt.Color(255, 255, 255));
        panel_configuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 167, 157), 3));
        panel_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_configuracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        panel_configuracion.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panel_configuracion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 349, 170));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Data-Find.png"))); // NOI18N
        jLabel39.setText("Consultar");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel39.setIconTextGap(-25);
        jLabel39.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        panel_configuracion.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 80));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Save.png"))); // NOI18N
        jLabel40.setText("Agregar");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel40.setIconTextGap(-22);
        jLabel40.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        panel_configuracion.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 90));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Data-Edit.png"))); // NOI18N
        jLabel44.setText("Modificar");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel44.setIconTextGap(-22);
        jLabel44.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        panel_configuracion.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 90));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Garbage-Closed.png"))); // NOI18N
        jLabel45.setText("Eliminar");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel45.setIconTextGap(-22);
        jLabel45.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        panel_configuracion.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 90));

        jLabel6.setText(":");
        panel_configuracion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 20, -1));

        jLabel7.setText(":");
        panel_configuracion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 10, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel_configuracion.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        panel_configuracion.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        panel_configuracion.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        panel_configuracion.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, -1));

        lbl_usuario5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_usuario5.setForeground(new java.awt.Color(0, 167, 157));
        lbl_usuario5.setText("GESTION DE HORARIOS");
        panel_configuracion.add(lbl_usuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Horario:");
        panel_configuracion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Hora de apertura:");
        panel_configuracion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Hora de cierre:");
        panel_configuracion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Obteniendo los valores de las filas
        int row = jTable1.getSelectedRow();
        //obteniendo los valores de la tabla
        String codigo = jTable1.getValueAt(row, 0).toString();
        String horario = jTable1.getValueAt(row, 1).toString();
        String hora1 = jTable1.getValueAt(row, 2).toString();
        String hora2 = jTable1.getValueAt(row, 3).toString();
        //mostrando en los jtexfield y jcombobox
        cod_horario = codigo;
        jTextField2.setText(horario);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            //hora apertura
            Date d = df.parse("2016-05-30 " + hora1 + ":00");
            Calendar gc = new GregorianCalendar();
            gc.setTime(d);
            int h1 = gc.get(gc.HOUR_OF_DAY);
            int m1 = gc.get(gc.MINUTE);
            jComboBox1.setSelectedIndex(h1);
            jComboBox2.setSelectedIndex(m1);
            
            //hora cierre
            Date d2 = df.parse("2016-05-30 " + hora2 + ":00");
            Calendar gc2 = new GregorianCalendar();
            gc2.setTime(d2);
            int h2 = gc2.get(gc.HOUR_OF_DAY);
            int m2 = gc2.get(gc.MINUTE);
            jComboBox3.setSelectedIndex(h2);
            jComboBox4.setSelectedIndex(m2);
            
        } catch (ParseException ex) {
            Logger.getLogger(Horario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        mthConsulta();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        if (jTextField2.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Campos vacios");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Horario obj = new Mto_Horario();
            //insertando los nuevos valores a los metodos de la clase
            int h1 = jComboBox1.getSelectedIndex();
            int m1 = jComboBox2.getSelectedIndex();
            int h2 = jComboBox3.getSelectedIndex();
            int m2 = jComboBox4.getSelectedIndex();
            if (h1 == h2){
                if (m2 <= m1){
                    JOptionPane.showMessageDialog(this, "ERROR: No puede ingresar horas menores o iguales que " + h1 + ":" + m1);
                } else if (m2 > m1){
                    obj.setHorario(jTextField2.getText());
                    String hora1 = (jComboBox1.getSelectedItem() + ":" + jComboBox2.getSelectedItem());
                    String hora2 = (jComboBox3.getSelectedItem() + ":" + jComboBox4.getSelectedItem());
                    obj.setHora_a(hora1);
                    obj.setHora_c(hora2);
                    //ejecuta el metodo y valida si se realizo satisfactoriamente
                    if(obj.MthGuardar()){
                        JOptionPane.showMessageDialog(this, "Datos guardados");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                    }
                //ejecuta el metodo de limpiar campos
                mthLimpiarCampos();
                mthConsulta();
                }
            } else if (h2 < h1){
                JOptionPane.showMessageDialog(this, "ERROR: No puede ingresar horas menores que " + h1 + ":" + m1);
            } else if (h2 > h1){
                obj.setHorario(jTextField2.getText());
                String hora1 = (jComboBox1.getSelectedItem() + ":" + jComboBox2.getSelectedItem());
                String hora2 = (jComboBox3.getSelectedItem() + ":" + jComboBox4.getSelectedItem());
                obj.setHora_a(hora1);
                obj.setHora_c(hora2);
                //ejecuta el metodo y valida si se realizo satisfactoriamente
                if(obj.MthGuardar()){
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                }
                //ejecuta el metodo de limpiar campos
                mthLimpiarCampos();
                mthConsulta();
            }
            
            
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        if (jTextField2.getText().equals("") || cod_horario == null){
            JOptionPane.showMessageDialog(this, "Campos vacios o registro no seleccionado.");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Horario obj = new Mto_Horario();
            //insertando los nuevos valores ingresados por los usuarios a los metodos de la clase
            obj.setHorario(jTextField2.getText());
            String hora1 = (jComboBox1.getSelectedItem() + ":" + jComboBox2.getSelectedItem());
            String hora2 = (jComboBox3.getSelectedItem() + ":" + jComboBox4.getSelectedItem());
            obj.setHora_a(hora1);
            obj.setHora_c(hora2);
            obj.setCodigo(Integer.parseInt(cod_horario));
            //ejecuta el metodo y valida si se realizo satisfactoriamente
            if (obj.mthModificar()){
                JOptionPane.showMessageDialog(this, "Datos modificados");
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
            //ejecuta el metodo de limpiar campos
            mthLimpiarCampos();
            mthConsulta();
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        if (cod_horario == null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado un registro para borrar.");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Horario obj = new Mto_Horario();
            //insertando el codigo al metodo setCodigo() en la clase
            obj.setCodigo(Integer.parseInt(cod_horario));
            //muestra un mensaje al usuario de confirmacion
            int eliminar = JOptionPane.showConfirmDialog(this, "Seguro?");
            //valida la respuesta del usuario
            if (eliminar == 0) {
                if (obj.mthEliminar()){
                    JOptionPane.showMessageDialog(this, "Datos eliminados");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }
            }
            //ejecuta el metodo de limpiar campos
            mthLimpiarCampos();
            mthConsulta();
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        //Codigo que valida y no deja escribir numeros y caracteres especiales
        char C= evt.getKeyChar();
        if (jTextField2.getText().length() >= 20) {
            evt.consume();
        }    
          if(Character.isDigit(C))
     {
        
        // evt.consume();
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         
         evt.consume();
     }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Administrador.FHor = false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_usuario5;
    private javax.swing.JPanel panel_configuracion;
    // End of variables declaration//GEN-END:variables
}
