/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Mantenimiento.Conexion;
import Mantenimiento.Mto_citas_reporte;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Christian
 */
public class Reporte_Citas_Recluso extends javax.swing.JFrame {

    /**
     * Creates new form Reporte_Citas_Recluso
     */
    public Reporte_Citas_Recluso() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    int cod;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_configuracion1 = new javax.swing.JPanel();
        lbl_usuario8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dpDesde = new org.jdesktop.swingx.JXDatePicker();
        dphasta = new org.jdesktop.swingx.JXDatePicker();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setResizable(false);

        panel_configuracion1.setBackground(new java.awt.Color(255, 255, 255));
        panel_configuracion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 167, 157), 3));
        panel_configuracion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_configuracion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_usuario8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_usuario8.setForeground(new java.awt.Color(0, 167, 157));
        lbl_usuario8.setText("Reportes Cita por Recluso");
        panel_configuracion1.add(lbl_usuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Seleccione un registro");
        panel_configuracion1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Hasta:");
        panel_configuracion1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        dpDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDesdeActionPerformed(evt);
            }
        });
        panel_configuracion1.add(dpDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 210, 30));

        dphasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dphastaActionPerformed(evt);
            }
        });
        panel_configuracion1.add(dphasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        jLabel90.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(0, 167, 157));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("IMPRIMIR");
        jLabel90.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel90.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel90.setName(""); // NOI18N
        jLabel90.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel90MouseClicked(evt);
            }
        });
        panel_configuracion1.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panel_configuracion1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 450, 230));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Desde:");
        panel_configuracion1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Filtrar por nombre");
        panel_configuracion1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        panel_configuracion1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_configuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_configuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpDesdeActionPerformed

    private void dphastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dphastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dphastaActionPerformed

    private void jLabel90MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel90MouseClicked
        Date fecha1 = dpDesde.getDate();
        Date fecha2 = dphasta.getDate();
        if (fecha1 == null || fecha2 == null){
            JOptionPane.showMessageDialog(null, "Campos vacios");
        } 
        else {
            if (fecha1.getTime() > fecha2.getTime()){
                JOptionPane.showMessageDialog(null, "El primer campo debe contener una fecha menor que el segundo");
            } 
            else {
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                Calendar gc = new GregorianCalendar();

                gc.setTime(fecha1);
                int dia1 = gc.get(gc.DAY_OF_MONTH);
                int mes1 = gc.get(gc.MONTH);
                int anio1 = gc.get(gc.YEAR);
                String fecha11 = dia1 + "-" + (mes1 + 1) + "-" + anio1;

                gc.setTime(fecha2);
                int dia2 = gc.get(gc.DAY_OF_MONTH);
                int mes2 = gc.get(gc.MONTH);
                int anio2 = gc.get(gc.YEAR);
                String fecha22 = dia2 + "-" + (mes2 + 1) + "-" + anio2;
        String path = ""; //Ubicacion del reporte
        try
        {

           //String nombre=this.txtNombreRe.getText();
           //String apellido=this.txtApellidoRe.getText();
           
           String url = "src/Reportes/ReporteCitasRecluso.jasper";
            Map parametro = new HashMap();
            parametro.put("fecha_inicio", fecha11);
            parametro.put("fecha_fin", fecha22);
            parametro.put("cod_recluso", cod);
            Connection cn = new Conexion().conectar();
            JasperPrint reporte = JasperFillManager.fillReport(url, parametro, cn);
            JasperViewer ventana = new JasperViewer(reporte,false);
            ventana.setTitle("Reportes comunes");
            ventana.setVisible(true);

        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
            }
        }
    }//GEN-LAST:event_jLabel90MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        ResultSet res;
        Mto_citas_reporte obj = new Mto_citas_reporte();
        obj.setNombre(jTextField1.getText());
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        res = obj.ConsultaReclusos();
        //ENCABEZADOS DE COLUMNAS
        dtm.setColumnIdentifiers(new Object[]{"codigo recluso", "Nombre", "Apellido", "Edad"});
        try{
            while(res.next()){
                //DATOS QUE SE CARGARAN A COLUMNAS
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                dtm.addRow(v);
                jTable1.setModel(dtm);

                //SE OCULTAN LAS COLUMNAS INNESESARIAS
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);

            }
        }catch(Exception ex){

        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int table = jTable1.getSelectedRow();
        int codigo = Integer.parseInt(jTable1.getValueAt(table, 0).toString());
        cod = codigo;
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte_Citas_Recluso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte_Citas_Recluso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte_Citas_Recluso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte_Citas_Recluso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte_Citas_Recluso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dpDesde;
    private org.jdesktop.swingx.JXDatePicker dphasta;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_usuario8;
    private javax.swing.JPanel panel_configuracion1;
    // End of variables declaration//GEN-END:variables
}
