/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Mantenimiento.Conexion;
import Mantenimiento.Mto_Sector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Sector extends javax.swing.JFrame {

    //Variable pública
    String cod_sector;
    
    /**
     * Creates new form Sector
     */
    public Sector() {
        initComponents();
        LlenarDatosEmpleado();
        LlenarDatosAgrupacion();
        LlenarDatosHorario();
        this.setLocationRelativeTo(null);
    }
    
    public void mthLimpiarCampos(){
        jTextField2.setText("");
        cod_sector = null;
    }
    
    public void mthConsultar(){
        ResultSet res;
        Mto_Sector obj = new Mto_Sector();
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        res = obj.Consulta();
        dtm.setColumnIdentifiers(new Object[]{"Codigo", "Nombre", "Encargado", "Agrupacion", "Horario"});
        try{
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));
                dtm.addRow(v);
                jTable1.setModel(dtm);
                //oculta columnas innecesarias
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            }
        }catch(Exception ex){

        }
    }
    
    Connection cn;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_configuracion1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lbl_usuario8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_configuracion1.setBackground(new java.awt.Color(255, 255, 255));
        panel_configuracion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 167, 157), 3));
        panel_configuracion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_configuracion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Horario:");
        panel_configuracion1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lbl_usuario8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_usuario8.setForeground(new java.awt.Color(0, 167, 157));
        lbl_usuario8.setText("GESTION DE SECTORES");
        panel_configuracion1.add(lbl_usuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Nombre:");
        panel_configuracion1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Empleado encargado:");
        panel_configuracion1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Agrupacion:");
        panel_configuracion1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        panel_configuracion1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 144, -1));

        panel_configuracion1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 144, -1));

        panel_configuracion1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 144, -1));

        panel_configuracion1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 144, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panel_configuracion1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 430, 180));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Data-Find.png"))); // NOI18N
        jLabel39.setText("Consultar");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel39.setIconTextGap(-25);
        jLabel39.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        panel_configuracion1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 80));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Save.png"))); // NOI18N
        jLabel40.setText("Agregar");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel40.setIconTextGap(-22);
        jLabel40.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        panel_configuracion1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 90));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Data-Edit.png"))); // NOI18N
        jLabel44.setText("Modificar");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel44.setIconTextGap(-22);
        jLabel44.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        panel_configuracion1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 90));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Garbage-Closed.png"))); // NOI18N
        jLabel45.setText("Eliminar");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel45.setIconTextGap(-22);
        jLabel45.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        panel_configuracion1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_configuracion1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_configuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Obteniendo los valores de las filas
        int row = jTable1.getSelectedRow();
        //guardando los valores de la tabla
        String codigo = jTable1.getValueAt(row, 0).toString();
        String sector = jTable1.getValueAt(row, 1).toString();
        String empleado = jTable1.getValueAt(row, 2).toString();
        String agrupacion = jTable1.getValueAt(row, 3).toString();
        String horario = jTable1.getValueAt(row, 4).toString();
        //mostrando en los jtexfield y jcombobox
        cod_sector = codigo;
        jTextField2.setText(sector);
        jComboBox1.setSelectedItem(empleado);
        jComboBox2.setSelectedItem(agrupacion);
        jComboBox3.setSelectedItem(horario);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        mthConsultar();
    }//GEN-LAST:event_jLabel39MouseClicked

    public void LlenarDatosEmpleado(){
        //Conectando la clase Conexion con la clase actual
        Conexion con = new Conexion();
        cn = con.conectar();
        try{
            //escribiendo la consulta 
            String sql = "SELECT * FROM Empleado where cod_cargo_empleado = 3";
            //enviando la consulta al cmd
            PreparedStatement cmd = cn.prepareStatement(sql);
            ResultSet rs = cmd.executeQuery();
            //mostrando los valores en el combo box
            while(rs.next()){
                jComboBox1.addItem(rs.getString("nombre_empleado"));
            }
        } catch (Exception ex){
            System.out.println("ERROR: " + ex.getMessage());
        }
    }
    
    public void LlenarDatosAgrupacion(){
        //Conectando la clase Conexion con la clase actual
        Conexion con = new Conexion();
        cn = con.conectar();
        try{
            //escribiendo la consulta 
            String sql = "SELECT * FROM Agrupacion";
            //enviando la consulta al cmd
            PreparedStatement cmd = cn.prepareStatement(sql);
            ResultSet rs = cmd.executeQuery();
            //mostrando los valores en el combo box
            while(rs.next()){
                jComboBox2.addItem(rs.getString("nombre_agrupacion"));
            }
        } catch (Exception ex){
            System.out.println("ERROR: " + ex.getMessage());
        }
    }
    
    public void LlenarDatosHorario(){
        //Conectando la clase Conexion con la clase actual
        Conexion con = new Conexion();
        cn = con.conectar();
        try{
            //escribiendo la consulta 
            String sql = "SELECT * FROM Horario";
            //enviando la consulta al cmd
            PreparedStatement cmd = cn.prepareStatement(sql);
            ResultSet rs = cmd.executeQuery();
            //mostrando los valores en el combo box
            while(rs.next()){
                jComboBox3.addItem(rs.getString("horario"));
            }
        } catch (Exception ex){
            System.out.println("ERROR: " + ex.getMessage());
        }
    }
    
    
    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        if (jTextField2.getText().equals("") || (jComboBox1.getSelectedIndex() == - 1) || (jComboBox2.getSelectedIndex() == - 1) || (jComboBox3.getSelectedIndex() == - 1)){
            JOptionPane.showMessageDialog(this, "Campos vacios");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Sector obj = new Mto_Sector();
            //insertando los nuevos valores a los metodos de la clase
            obj.setSector(jTextField2.getText());
            obj.setEmpleado((jComboBox1.getSelectedIndex() + 1));
            obj.setAgrupacion((jComboBox2.getSelectedIndex() + 1));
            obj.setHorario((jComboBox3.getSelectedIndex() + 1));
            //ejecuta el metodo y valida si se realizo satisfactoriamente
            if(obj.MthGuardar()){
                JOptionPane.showMessageDialog(this, "Datos guardados");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar los datos");
            }
            //ejecuta el metodo de limpiar campos
            mthLimpiarCampos();
            mthConsultar();
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        if (jTextField2.getText().equals("") || cod_sector == null || (jComboBox1.getSelectedIndex() == - 1) || (jComboBox2.getSelectedIndex() == - 1) || (jComboBox3.getSelectedIndex() == - 1)){
            JOptionPane.showMessageDialog(this, "Campos vacios o registro no seleccionado.");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Sector obj = new Mto_Sector();
            //insertando los nuevos valores ingresados por los usuarios a los metodos de la clase
            obj.setSector(jTextField2.getText());
            obj.setEmpleado((jComboBox1.getSelectedIndex() + 1));
            obj.setAgrupacion((jComboBox2.getSelectedIndex() + 1));
            obj.setHorario((jComboBox3.getSelectedIndex() + 1));
            obj.setCodigo(Integer.parseInt(cod_sector));
            //ejecuta el metodo y valida si se realizo satisfactoriamente
            if (obj.mthModificar()){
                JOptionPane.showMessageDialog(this, "Datos modificados");
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
            //ejecuta el metodo de limpiar campos
            mthLimpiarCampos();
            mthConsultar();
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        if (cod_sector == null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado un registro para borrar.");
        } else {
            //declarando variable de la clase que contiene los metodos
            Mto_Sector obj = new Mto_Sector();
            //insertando el codigo al metodo setCodigo() en la clase
            obj.setCodigo(Integer.parseInt(cod_sector));
            //muestra un mensaje al usuario de confirmacion
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Seguro?");
            //valida la respuesta del usuario
            if (eliminar == 0) {
                if (obj.mthEliminar()){
                    JOptionPane.showMessageDialog(this, "Datos eliminados");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }
            }
            //ejecuta el metodo de limpiar campos
            mthLimpiarCampos();
            mthConsultar();
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Administrador.FSec = false;
    }//GEN-LAST:event_formWindowClosing

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        //Codigo que valida y no deja escribir numeros y caracteres especiales
        char C= evt.getKeyChar();
        if (jTextField2.getText().length() >= 25) {
            evt.consume();
        }

        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {

            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_usuario8;
    private javax.swing.JPanel panel_configuracion1;
    // End of variables declaration//GEN-END:variables
}
